config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  root 'professionals#index'

  devise_for :users, controllers: { registrations: "registrations"}

  get 'professionals' => 'professionals#index', as: :professionals
  get 'professionals/:id' => 'professionals#show', as: :professional
  get 'professionals/:id/edit' => 'professionals#edit', as: :edit_professional
  put 'professionals/:id' => 'professionals#update'
  patch 'professionals/:id' => 'professionals#update'
  delete 'professionals/:id' => 'professionals#destroy'

  get 'physicians' => 'physicians#index', as: :physicians
  get 'physicians/new' => 'physicians#new', as: :new_physician
  post 'physicians' => 'physicians#create'

  get 'attorneys' => 'attorneys#index', as: :attorneys
  get 'attorneys/new' => 'attorneys#new', as: :new_attorney
  post 'attorneys' => 'attorneys#create'

  get 'professionals/:id/reviews/new' => 'reviews#new', as: :new_review
  get 'reviews/:id' => 'reviews#show', as: :review
  get 'reviews/:id/edit' => 'reviews#edit', as: :edit_review
  post 'reviews' => 'reviews#create'
  put 'reviews/:id' => 'reviews#update'
  patch 'reviews/:id' => 'reviews#update'
  delete 'reviews/:id' => 'reviews#destroy'

end

app/models/professional.rb
class Professional < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  validates :bio, presence: true
  validates :placeId, presence: true

  has_many :reviews
  belongs_to :profession

  has_attached_file :image, styles: { image_index: "250x350>", image_show: "325x475>" }, default_url: "/images/missing.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def full_name
    [first_name, last_name].join(" ")
  end

  def self.create_attorney
    profession = Profession.find_by(name: "Attorney")
    profession.professionals.new
  end

  def self.create_physician
    profession = Profession.find_by(name: "Physician")
    profession.professionals.new
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit]

  def index
    @professionals = Professional.all.order(average_rating: :DESC)
  end

  def show
    @professional = Professional.find(params[:id])
  end

  def edit
    @professional = Professional.find(params[:id])
  end

  def update
    @professional = Professional.find(params[:id])
    if @professional.update(professional_params)
      redirect_to professional_path(@professional)
    else
      render :edit
    end
  end

  def destroy
    @professional = Professional.find_by id: params[:id]
    @professional.destroy
    redirect_to root_path
  end

  private

  private

  def professional_params
    params
      .require(:professional)
      .permit(:first_name, :last_name, :address, :phone_number,
              :email, :bio, :image, :placeId)
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/views/professionals/_form.html.erb
<%= simple_form_for model, url: form_path do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :first_name, label: "First Name" %>
  <%= f.input :last_name, label: "Last Name" %>
  <%= f.input :address, label: "Loacated At" %>
  <%= f.input :placeId, label: "Google Maps PlaceID" %>
  <%= f.input :email %>
  <%= f.input :phone_number %>
  <%= f.input :bio, label: "Bio" %>
  <%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/professionals/edit.html.erb
<div class="col-md-10 col-md-offset-1">

  <div class="new-physician-form">

    <h1>Edit Professional</h1>
    <%= render partial: 'professionals/form',
               locals: { model: @professional, form_path: professional_path } %>
  </div>

</div>

app/views/professionals/index.html.erb
<h1 class="page-header">Professionals:</h1>
<% if @professionals.empty? %>
  <h1>There are no Attorney currently in this category</h1>
<% else %>
<div class="row">

    <% @professionals.each do |attorney| %>
      <div class="col-md-3">
        <h3 class="physician-full-name"><%= attorney.full_name %></h3>
        <div class="average-review-rating" data-score=<%= attorney.average_rating %>></div>
        <span class="number-of-reviews">Based on <%= attorney.reviews.count %> reviews</span>
        <%= link_to professional_path(attorney.id) do %>
        <%= image_tag attorney.image.url, class: "attorney" %>
        <% end %>

      </div>
    <% end %>
</div>
<% end %>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/professionals/show.html.erb
<!-- Showing physician Image -->
<div class="row">
    <div class="col-md-4">
        <%= image_tag @professional.image.url, class: "physician-show" %>
    </div>
    <!-- SHowing Physician Info  -->
    <div class="col-md-8">
        <div class="physician-info">

            <h2 class="physician-full-name"><%= @professional.full_name %></h2>
            <h4 class="address"><%= @professional.address %></h4>
            <h4 class="avg-rating">Average Rating</h4>
            <div class="average-review-rating" data-score=<%= @professional.average_rating %>></div>
            <span class="number-of-reviews">Based on
                <%= @professional.reviews.count %>
                reviews</span>
            <p class="physician-bio"><%= @professional.bio %></p>
            <div class="links btn-group">
                <%= link_to "Go Back", professionals_path(@professional.id), class: "btn btn-custom"  %>
                <!-- SHowing back button and conditional for only the user that created Physician to Edit and Delete  -->
                <% if user_signed_in? %>
                <%= link_to "Edit", edit_professional_path(@professional.id), class: "btn btn-custom" %>
                <%= link_to "Delete", professional_path(@professional.id), method: :delete, data: { confirm: "Are You Sure?"}, class: "btn btn-custom" %>
                <% end %>
            </div>
        </div>
    </div>

    <div class="col-md-8">
      <div class="reviews">
        <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyC2hpysVWx6eblzUa9QQsKQJV5I7KQsDlk&q=place_id:<%= @professional.placeId %>">
        </iframe>
      </div>
    </div>

    <!-- SHowing Add Review button And Reviews  -->
    <div class="col-md-8">
        <div class="reviews">

            <h1>Reviews</h1>
            <%= render @professional.reviews %>
            <!--where the review/rating  -->
            <div>
                <%= link_to "Add Review", new_review_path(@professional.id), class: "btn-custom" %>
            </div>
        </div>
    </div>
</div>
<!-- SHowing Add Review button And Reviews  -->

<script>
    $('.review-rating').raty({
        readOnly: true,
        score: function () {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

<script>
    $('.average-review-rating').raty({
        readOnly: true,
        path: '/assets/',
        score: function () {
            return $(this).attr('data-score')
        }
    });
</script>