config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  root 'professionals#index'

  devise_for :users, controllers: { registrations: "registrations"}

  get 'professionals' => 'professionals#index', as: :professionals
  get 'professionals/:id' => 'professionals#show', as: :professional
  get 'professionals/:id/edit' => 'professionals#edit', as: :edit_professional
  put 'professionals/:id' => 'professionals#update'
  patch 'professionals/:id' => 'professionals#update'
  delete 'professionals/:id' => 'professionals#destroy'

  get 'physicians' => 'physicians#index', as: :physicians
  get 'physicians/new' => 'physicians#new', as: :new_physician
  post 'physicians' => 'physicians#create'

  get 'attorneys' => 'attorneys#index', as: :attorneys
  get 'attorneys/new' => 'attorneys#new', as: :new_attorney
  post 'attorneys' => 'attorneys#create'

  get 'professionals/:id/reviews/new' => 'reviews#new', as: :new_review
  get 'reviews/:id' => 'reviews#show', as: :review
  get 'reviews/:id/edit' => 'reviews#edit', as: :edit_review
  post 'reviews' => 'reviews#create'
  put 'reviews/:id' => 'reviews#update'
  patch 'reviews/:id' => 'reviews#update'
  delete 'reviews/:id' => 'reviews#destroy'

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_user!

  def new

  end

  def update
    token = params[:stripeToken]

    customer = Stripe::Customer.create(
        card: token,
        plan: 2255,
        email: current_user.email
        )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save

    redirect_to professionals_path
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1000"></script><span> $10.99 per month, cancel at any time.</span>
<% end %>

app/views/subscribers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
            <div class="panel-body">
                <h2>Final Signup Step</h2>
                <h4>This is the final step to give you full access to</h4>
                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>