config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  root 'professionals#index'

  devise_for :users, controllers: { registrations: "registrations"}

  get 'professionals' => 'professionals#index', as: :professionals
  get 'professionals/:id' => 'professionals#show', as: :professional
  get 'professionals/:id/edit' => 'professionals#edit', as: :edit_professional
  put 'professionals/:id' => 'professionals#update'
  patch 'professionals/:id' => 'professionals#update'
  delete 'professionals/:id' => 'professionals#destroy'

  get 'physicians' => 'physicians#index', as: :physicians
  get 'physicians/new' => 'physicians#new', as: :new_physician
  post 'physicians' => 'physicians#create'

  get 'attorneys' => 'attorneys#index', as: :attorneys
  get 'attorneys/new' => 'attorneys#new', as: :new_attorney
  post 'attorneys' => 'attorneys#create'

  get 'professionals/:id/reviews/new' => 'reviews#new', as: :new_review
  get 'reviews/:id' => 'reviews#show', as: :review
  get 'reviews/:id/edit' => 'reviews#edit', as: :edit_review
  post 'reviews' => 'reviews#create'
  put 'reviews/:id' => 'reviews#update'
  patch 'reviews/:id' => 'reviews#update'
  delete 'reviews/:id' => 'reviews#destroy'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @professional = Professional.find(params[:id])
    @review = @professional.reviews.new
  end

  def create
    @review = Review.new(review_params)
    professional = @review.professional
    @review.user_id = current_user.id
    if @review.save
      avg_rating = professional.reviews.average(:rating).round(2)
      professional.average_rating = avg_rating
      professional.save
      redirect_to professional_path(@review.professional.id)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to professional_path(@review.professional.id)
    else
      render :edit

    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to professional_path(@review.professional.id)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :professional_id)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<!-- <%= debug @professional %> -->
<%= simple_form_for @review do |f| %>
<div id="rating-form">
  <label>Rating</label>
</div>
  <%= f.input :comment %>
  <%= f.button :submit, :class => 'btn-custom2' %>
  <%= f.hidden_field :professional_id, value: @professional.id %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<div class="review">
  <div class="review-rating" data-score="<%= review.rating %>"></div>
  <p class="review-comment"><%= review.comment %></p>

  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>

    <div class="links btn-group">
      <%= link_to "Edit", edit_review_path(review.id), class: "btn btn-custom"  %>
      <%= link_to "Delete", review_path(review.id), method: :delete, data: {confirm: "Are You Sure?"}, class: "btn btn-custom" %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">

  <div class="edit-review-form">

    <h1>Edit Review</h1>

    <%= simple_form_for([@physician, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, :class => 'btn-custom2' %>
    <% end %>
  </div>
</div>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">

  <div class="new-review-form">

  <h1>New Review</h1>

  <%= render 'form' %>
  </div>
</div>