config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  root 'professionals#index'

  devise_for :users, controllers: { registrations: "registrations"}

  get 'professionals' => 'professionals#index', as: :professionals
  get 'professionals/:id' => 'professionals#show', as: :professional
  get 'professionals/:id/edit' => 'professionals#edit', as: :edit_professional
  put 'professionals/:id' => 'professionals#update'
  patch 'professionals/:id' => 'professionals#update'
  delete 'professionals/:id' => 'professionals#destroy'

  get 'physicians' => 'physicians#index', as: :physicians
  get 'physicians/new' => 'physicians#new', as: :new_physician
  post 'physicians' => 'physicians#create'

  get 'attorneys' => 'attorneys#index', as: :attorneys
  get 'attorneys/new' => 'attorneys#new', as: :new_attorney
  post 'attorneys' => 'attorneys#create'

  get 'professionals/:id/reviews/new' => 'reviews#new', as: :new_review
  get 'reviews/:id' => 'reviews#show', as: :review
  get 'reviews/:id/edit' => 'reviews#edit', as: :edit_review
  post 'reviews' => 'reviews#create'
  put 'reviews/:id' => 'reviews#update'
  patch 'reviews/:id' => 'reviews#update'
  delete 'reviews/:id' => 'reviews#destroy'

end

app/models/profession.rb
class Profession < ActiveRecord::Base
  has_many :professionals
end

app/models/professional.rb
class Professional < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true
  validates :bio, presence: true
  validates :placeId, presence: true

  has_many :reviews
  belongs_to :profession

  has_attached_file :image, styles: { image_index: "250x350>", image_show: "325x475>" }, default_url: "/images/missing.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def full_name
    [first_name, last_name].join(" ")
  end

  def self.create_attorney
    profession = Profession.find_by(name: "Attorney")
    profession.professionals.new
  end

  def self.create_physician
    profession = Profession.find_by(name: "Physician")
    profession.professionals.new
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :professional_id, presence: true
  validates :user_id, presence: true
  validates :rating, presence: true

  belongs_to :professional
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :physicians
  has_many :attorneys
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attorneys_controller.rb
class AttorneysController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    profession = Profession.find_by(name: 'Attorney')
    @attorneys = profession.professionals.all.order(average_rating: :DESC)
  end

  def show
    @attorney = Professional.find(params[:id])
  end

  def new
    @attorney = Professional.new
  end

  def create
    @attorney = Professional.new(attorney_params)
    @attorney.profession = Profession.find_by(name: 'Attorney')
    if @attorney.save
      redirect_to attorneys_path
    else
      render :new
    end
  end

  def edit
    @attorney = Professional.find(params[:id])
  end

  def update
    @attorney = Professional.find(params[:id])
    if @attorney.update(attorney_params)
      redirect_to attorney_path(@attorney)
    else
      render :edit
    end
  end

  def destroy
    @attorney = Professional.find_by id: params[:id]
    @attorney.destroy
    redirect_to attorneys_path
  end

  private

  def attorney_params
    params
      .require(:professional)
      .permit(:first_name, :last_name, :address,
             :email, :phone_number, :bio, :image, :placeId)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new

  end

  def create

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    profession = Profession.find_by(name: 'Physician')
    @physicians = profession.professionals.all.order(average_rating: :DESC)
  end

  def show
    @physician = Professional.find(params[:id])
  end

  def new
    @physician = Professional.new
  end

  def create
    profession = Profession.find_by(name: 'Physician')
    @physician = profession.professionals.new(physician_params)
    if @physician.save
      redirect_to physicians_path
    else
      render :new
    end
  end

  def edit
    @physician = Professional.find(params[:id])
  end

  def update
    @physician = Professional.find(params[:id])
    if @physician.update(physician_params)
      redirect_to physician_path(@physician)
    else
      render :edit
    end
  end

  def destroy
    @physician = Professional.find_by id: params[:id]
    @physician.destroy
    redirect_to physicians_path
  end

  private

  def physician_params
    params
      .require(:professional)
      .permit(:first_name, :last_name, :address, :phone_number,
              :email, :bio, :image, :placeId)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @professional = Professional.find(params[:id])
    @review = @professional.reviews.new
  end

  def create
    @review = Review.new(review_params)
    professional = @review.professional
    @review.user_id = current_user.id
    if @review.save
      avg_rating = professional.reviews.average(:rating).round(2)
      professional.average_rating = avg_rating
      professional.save
      redirect_to professional_path(@review.professional.id)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to professional_path(@review.professional.id)
    else
      render :edit

    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to professional_path(@review.professional.id)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :professional_id)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_filter :authenticate_user!

  def new

  end

  def update
    token = params[:stripeToken]

    customer = Stripe::Customer.create(
        card: token,
        plan: 2255,
        email: current_user.email
        )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save

    redirect_to professionals_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attorneys_helper.rb
module AttorneysHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hurt-At-Work</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Hurt At Work", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">View Professional
                <span class="carret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'View Physicians', physicians_path, class: "link" %></li>
                <li><%= link_to 'View Attorneys', attorneys_path, class: "link" %></li>
              </ul>
            </li>
          <% end %>
          
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Create Professional
                <span class="carret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Add Physicians',new_physician_path, class: "link" %></li>
                <li><%= link_to 'Add Attorneys', new_attorney_path, class: "link" %></li>
              </ul>
            </li>
          <% end %>

          <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="notice text-center"><%= notice %></p>
      <p class="alert text-center"><%= alert %></p>
      <br>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_professional.html.erb
<!-- Showing physician Image -->
<div class="row">
  <div class="col-md-4">
    <%= image_tag professional.image.url(:image_show), class: "physician-show" %>
  </div>
  <!-- SHowing Physician Info  -->
  <div class="col-md-8">
    <div class="physician-info">

      <h2 class="physician-full-name"><%= professional.full_name %></h2>
      <h4 class="avg-rating">Average Rating</h4>
      <div class="average-review-rating" data-score=<%= professional.average_rating %>></div>
      <span class="number-of-reviews">Based on <%= professional.reviews.count %> reviews</span>
      <p class="physician-bio"><%= professional.bio %></p>

    </div>
  </div>
</div>
<!-- SHowing Add Review button And Reviews  -->

<div class="row">
  <div class="col-md-4">
    <div class="reviews">

      <h1>Reviews</h1>
      <%= render professional.reviews %>
      <!--where the review/rating  -->
      <div>
        <%= link_to "Add Review", new_review_path(professional.id), class: "btn-custom" %>
      </div>
    </div>
  </div>
</div>
<!-- SHowing back button and conditional for only the user that created Physician to Edit and Delete  -->
<div class="links btn-group">
  <%= link_to "Go Back", root_path, class: "btn btn-custom"  %>

  <% if user_signed_in? %>
      <%= link_to "Edit", edit_physician_path(professional.id), class: "btn btn-custom" %>
      <%= link_to "Delete", professional_path(professional.id), method: :delete, data: { confirm: "Are You Sure?"}, class: "btn btn-custom" %>
  <% end %>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>